### ISSUE TITLE
Finalize BiliBili Tracking

### ISSUE THREAD

**Issue by noaione** [ihateani-me/vtscheduler-ts#5]
So... what's left?

- [ ] A proper managing of rate limit.
- [x] Use the new tasks class format.
- [ ] Handling of schedule and live properly, probably follow Twitch schedule format
